# Generated by Django 4.1.2 on 2022-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='description',
            field=models.TextField(max_length=900, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='product_name',
            field=models.CharField(max_length=124, verbose_name='Product name'),
        ),
    ]
